;=====================================================================
; Configuration file for Canon MF/LBP Network Setup Tool.
; Copyright (C) 2012 Canon Inc.
;=====================================================================

[DeviceName]
Canon LBP7100C/7110C
Canon LBP6030/6040/6018L
Canon LBP6230/6240
Canon LBP8100
Canon LBP151

[Timeout]
USBTimeout=10
DevconfigConfigTimeout=40
DevconfigDiscoverTimeout=3
UnknownIPSetupTimeout=1
RebootWaitTimeout=10

[CommunityName]
SNMPCommunityName=public

[ApplicationInfo]
Version=2.30
Copyright=Copyright CANON INC. 2012

[Canon LBP7100C/7110C]
USBPnPID=CanonLBP7100C/7110C
MIBProductID=102
WPS=1
AOSS=0
Easy=0
OnePush=0
LEDInterval=500
Arch=1
ModelName=LBP7110Cw LBP7100Cn
WirelessModel=BF000002 BF000003
WiredModel=BF000001 BF000002 BF000003

[Canon LBP6030/6040/6018L]
USBPnPID=CanonLBP6030/6040/6018L
MIBProductID=107
WPS=1
AOSS=0
Easy=0
OnePush=1
LEDInterval=250
Arch=1
ModelName=LBP6030 LBP6040 LBP6030/6030B/6018L LBP6030w/6018w
WirelessModel=AF000002
WiredModel=

[Canon LBP6230/6240]
USBPnPID=CanonLBP6230/6240
MIBProductID=108
WPS=1
AOSS=0
Easy=0
OnePush=1
LEDInterval=250
Arch=1
ModelName=LBP6230 LBP6240 LBP6230dn LBP6230dw
WirelessModel=AF010002
WiredModel=AF010001 AF010002

[Canon LBP8100]
USBPnPID=CanonLBP8100
MIBProductID=112
WPS=0
AOSS=0
Easy=0
OnePush=0
LEDInterval=250
Arch=1
ModelName=LBP8100 LBP8100n
WirelessModel=
WiredModel=AF020001

[Canon LBP151]
USBPnPID=CanonLBP151
MIBProductID=113
WPS=1
AOSS=0
Easy=0
OnePush=1
LEDInterval=250
Arch=2
ModelName=LBP151
WirelessModel=AF030001
WiredModel=AF030001
